PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS patients (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, age INTEGER, phone TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS medicines (id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id INTEGER NOT NULL, name TEXT NOT NULL, dosage TEXT NOT NULL, description TEXT DEFAULT '', active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), FOREIGN KEY(patient_id) REFERENCES patients(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS schedules (id INTEGER PRIMARY KEY AUTOINCREMENT, medicine_id INTEGER NOT NULL, time TEXT NOT NULL, frequency TEXT NOT NULL CHECK(frequency IN ('DAILY','WEEKLY','CUSTOM')), start_date TEXT NOT NULL, end_date TEXT, enabled INTEGER NOT NULL DEFAULT 1, weekdays TEXT DEFAULT '', FOREIGN KEY(medicine_id) REFERENCES medicines(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS reminder_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, medicine_id INTEGER NOT NULL, schedule_id INTEGER, scheduled_time TEXT NOT NULL, triggered_at TEXT, confirmed_at TEXT, status TEXT NOT NULL CHECK(status IN ('SCHEDULED','TRIGGERED','TAKEN','MISSED','PENDING')), device_id TEXT, is_test INTEGER NOT NULL DEFAULT 0, UNIQUE(medicine_id, scheduled_time), FOREIGN KEY(medicine_id) REFERENCES medicines(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS devices (id INTEGER PRIMARY KEY AUTOINCREMENT, device_name TEXT NOT NULL, device_uid TEXT NOT NULL UNIQUE, last_seen TEXT, status TEXT NOT NULL DEFAULT 'OFFLINE', wifi_rssi INTEGER, rtc_status TEXT DEFAULT 'UNKNOWN', firmware_version TEXT DEFAULT '1.0.0');
CREATE TABLE IF NOT EXISTS device_events (id INTEGER PRIMARY KEY AUTOINCREMENT, device_id TEXT NOT NULL, event_type TEXT NOT NULL, event_time TEXT NOT NULL, payload TEXT DEFAULT '{}');
INSERT OR IGNORE INTO patients (id,name,age,phone) VALUES (1,'Demo Patient',21,'');
INSERT OR IGNORE INTO devices (device_name,device_uid,status,rtc_status,firmware_version) VALUES ('ESP32 Medicine Device','ESP32-MED-001','OFFLINE','UNKNOWN','1.0.0');
