require('dotenv').config();
const express=require('express'), cors=require('cors'), path=require('path');
const {run,get,all,init}=require('./database');
const app=express(); const PORT=process.env.PORT||3000; const API_KEY=process.env.ESP32_API_KEY||'change-this-key';
app.use(cors()); app.use(express.json());
const now=()=>new Date().toISOString(); const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:process.env.TIMEZONE||'Asia/Kolkata'}).format(new Date());
const deviceAuth=(req,res,next)=>{if(req.get('x-api-key')!==API_KEY)return res.status(401).json({error:'Invalid device API key'});next()};
app.get('/api/health',(req,res)=>res.json({ok:true,service:'smart-medicine-reminder',timezone:process.env.TIMEZONE||'Asia/Kolkata',timestamp:now()}));
app.get('/api/medicines',async(req,res)=>{try{res.json(await all(`SELECT m.*,s.id schedule_id,s.time,s.frequency,s.start_date,s.end_date,s.enabled,s.weekdays FROM medicines m LEFT JOIN schedules s ON s.medicine_id=m.id WHERE m.active=1 ORDER BY m.name,s.time`))}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/medicines/:id',async(req,res)=>{try{const m=await get('SELECT * FROM medicines WHERE id=?',[req.params.id]);if(!m)return res.status(404).json({error:'Medicine not found'});m.schedules=await all('SELECT * FROM schedules WHERE medicine_id=?',[m.id]);res.json(m)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/medicines',async(req,res)=>{const {name,dosage,description='',time,frequency='DAILY',startDate=today(),endDate='',weekdays=''}=req.body;if(!name||!dosage||!/^[0-2]\d:[0-5]\d$/.test(time||'')||!['DAILY','WEEKLY','CUSTOM'].includes(frequency))return res.status(400).json({error:'name, dosage, valid time (HH:MM), and frequency are required'});try{const m=await run('INSERT INTO medicines(patient_id,name,dosage,description) VALUES(1,?,?,?)',[name.trim(),dosage.trim(),description]);await run('INSERT INTO schedules(medicine_id,time,frequency,start_date,end_date,weekdays) VALUES(?,?,?,?,?,?)',[m.id,time,frequency,startDate,endDate||null,weekdays]);res.status(201).json(await get('SELECT * FROM medicines WHERE id=?',[m.id]))}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/medicines/:id',async(req,res)=>{const {name,dosage,description='',time,frequency='DAILY',startDate=today(),endDate='',weekdays=''}=req.body;if(!name||!dosage||!/^[0-2]\d:[0-5]\d$/.test(time||'')||!['DAILY','WEEKLY','CUSTOM'].includes(frequency))return res.status(400).json({error:'Invalid medicine data'});try{const existing=await get('SELECT * FROM medicines WHERE id=?',[req.params.id]);if(!existing)return res.status(404).json({error:'Medicine not found'});await run('UPDATE medicines SET name=?,dosage=?,description=?,updated_at=datetime(\'now\') WHERE id=?',[name,dosage,description,req.params.id]);await run('UPDATE schedules SET time=?,frequency=?,start_date=?,end_date=?,weekdays=? WHERE medicine_id=?',[time,frequency,startDate,endDate||null,weekdays,req.params.id]);res.json({message:'Updated'})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/medicines/:id',async(req,res)=>{try{const r=await run('UPDATE medicines SET active=0 WHERE id=?',[req.params.id]);if(!r.changes)return res.status(404).json({error:'Medicine not found'});res.status(204).end()}catch(e){res.status(500).json({error:e.message})}});
async function ensureTodayRows(){const d=today();const schedules=await all(`SELECT m.id medicine_id,s.id schedule_id,s.time FROM medicines m JOIN schedules s ON s.medicine_id=m.id WHERE m.active=1 AND s.enabled=1 AND s.start_date<=? AND (s.end_date IS NULL OR s.end_date='' OR s.end_date>=?)`,[d,d]);for(const s of schedules){const scheduled=`${d}T${s.time}:00`;await run('INSERT OR IGNORE INTO reminder_logs(medicine_id,schedule_id,scheduled_time,status) VALUES(?,?,?,?)',[s.medicine_id,s.schedule_id,scheduled,'PENDING']);}}
async function todayRows(){const d=today();await ensureTodayRows();return all(`SELECT r.*,m.name,m.dosage,s.time,s.frequency FROM reminder_logs r JOIN medicines m ON m.id=r.medicine_id LEFT JOIN schedules s ON s.id=r.schedule_id WHERE substr(r.scheduled_time,1,10)=? ORDER BY r.scheduled_time`,[d])}
app.get('/api/reminders/today',async(req,res)=>{try{const rows=await todayRows();res.json(rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/reminders/history',async(req,res)=>{try{res.json(await all(`SELECT r.*,m.name,m.dosage,s.time FROM reminder_logs r JOIN medicines m ON m.id=r.medicine_id LEFT JOIN schedules s ON s.id=r.schedule_id ORDER BY r.scheduled_time DESC LIMIT 200`))}catch(e){res.status(500).json({error:e.message})}});
async function setLog(body,status){const {medicineId,scheduledTime,deviceId='ESP32-MED-001',isTest=0}=body;if(!medicineId||!scheduledTime)throw Object.assign(new Error('medicineId and scheduledTime are required'),{status:400});const existing=await get('SELECT * FROM reminder_logs WHERE medicine_id=? AND scheduled_time=?',[medicineId,scheduledTime]);if(existing){await run(`UPDATE reminder_logs SET status=?,confirmed_at=? WHERE id=?`,[status,status==='TAKEN'?now():null,existing.id]);return existing.id}const r=await run('INSERT INTO reminder_logs(medicine_id,scheduled_time,triggered_at,confirmed_at,status,device_id,is_test) VALUES(?,?,?,?,?,?,?)',[medicineId,scheduledTime,now(),status==='TAKEN'?now():null,status,deviceId,isTest]);return r.id}
app.post('/api/reminders/taken',async(req,res)=>{try{const id=await setLog(req.body,'TAKEN');res.status(201).json({id,status:'TAKEN'})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.post('/api/reminders/missed',async(req,res)=>{try{const id=await setLog(req.body,'MISSED');res.status(201).json({id,status:'MISSED'})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.get('/api/esp32/schedule',deviceAuth,async(req,res)=>{try{const rows=await all(`SELECT m.id medicineId,m.name,m.dosage,s.time,s.frequency,s.start_date startDate,s.end_date endDate,s.weekdays FROM medicines m JOIN schedules s ON s.medicine_id=m.id WHERE m.active=1 AND s.enabled=1`);const testReminders=await all(`SELECT r.id,r.medicine_id medicineId,r.scheduled_time scheduledTime,m.name,m.dosage FROM reminder_logs r JOIN medicines m ON m.id=r.medicine_id WHERE r.is_test=1 AND r.status='TRIGGERED' ORDER BY r.id DESC LIMIT 5`);res.json({deviceId:req.get('x-device-id')||'ESP32-MED-001',timezone:process.env.TIMEZONE||'Asia/Kolkata',schedules:rows,testReminders})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/esp32/events',deviceAuth,async(req,res)=>{try{const {deviceId='ESP32-MED-001',eventType,eventTime=now(),medicineId,scheduledTime,isTest=0}=req.body;if(!eventType)return res.status(400).json({error:'eventType is required'});await run('INSERT INTO device_events(device_id,event_type,event_time,payload) VALUES(?,?,?,?)',[deviceId,eventType,eventTime,JSON.stringify(req.body)]);let logId=null;if(eventType==='MEDICINE_TAKEN'&&medicineId)logId=await setLog({medicineId,scheduledTime:scheduledTime||eventTime,deviceId,isTest},'TAKEN');if(eventType==='MEDICINE_MISSED'&&medicineId)logId=await setLog({medicineId,scheduledTime:scheduledTime||eventTime,deviceId,isTest},'MISSED');res.status(201).json({message:'Event stored',logId})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.post('/api/esp32/heartbeat',deviceAuth,async(req,res)=>{try{const {deviceId='ESP32-MED-001',wifiRssi=null,rtcStatus='SYNCED',firmwareVersion='1.0.0'}=req.body;await run(`INSERT INTO devices(device_name,device_uid,last_seen,status,wifi_rssi,rtc_status,firmware_version) VALUES(?,?,?,?,?,?,?) ON CONFLICT(device_uid) DO UPDATE SET last_seen=excluded.last_seen,status='ONLINE',wifi_rssi=excluded.wifi_rssi,rtc_status=excluded.rtc_status,firmware_version=excluded.firmware_version`,['ESP32 Medicine Device',deviceId,now(),'ONLINE',wifiRssi,rtcStatus,firmwareVersion]);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/esp32/status',async(req,res)=>{try{let d=await get('SELECT * FROM devices ORDER BY id LIMIT 1');if(!d)return res.json({status:'OFFLINE'});if(d.last_seen&&Date.now()-new Date(d.last_seen).getTime()>120000)d.status='OFFLINE';res.json(d)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/test-reminder',async(req,res)=>{try{const med=await get('SELECT m.id,m.name,m.dosage,s.id schedule_id FROM medicines m JOIN schedules s ON s.medicine_id=m.id WHERE m.active=1 ORDER BY m.id LIMIT 1');if(!med)return res.status(400).json({error:'Add a medicine first'});const ts=now();const id=await setLog({medicineId:med.id,scheduledTime:ts,deviceId:'ESP32-MED-001',isTest:1},'TRIGGERED');res.status(201).json({id,medicineId:med.id,status:'TRIGGERED',message:'Test reminder created'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/dashboard',async(req,res)=>{try{const meds=await all('SELECT id FROM medicines WHERE active=1'),rows=await todayRows(),device=await get('SELECT * FROM devices ORDER BY id LIMIT 1');res.json({totalMedicines:meds.length,todayCount:rows.length,taken:rows.filter(r=>r.status==='TAKEN').length,pending:rows.filter(r=>['PENDING','TRIGGERED'].includes(r.status)).length,missed:rows.filter(r=>r.status==='MISSED').length,device:device||{status:'OFFLINE'}})}catch(e){res.status(500).json({error:e.message})}});
app.use(express.static(path.join(__dirname,'../frontend')));
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Smart Medicine Reminder API running on http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
module.exports=app;
